.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LIBVALHALLA-TEST "1" "10/12/2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
libvalhalla-test \- a test media indexing utility which uses libvalhalla
.SH SYNOPSIS
.B libvalhalla-test
[\fIoptions \fR...] \fIpaths \fR...
.SH DESCRIPTION
This manual page documents briefly the \fBlibvalhalla-test\fP command.
.PP
\fBlibvalhalla-test\fP is a command-line media indexing tool which uses 
libvalhalla. It is mainly used to test and exercise libvalhalla capabilities.
.SH OPTIONS
.TP
\fB\-h\fR \fB\-\-help\fR
this help
.TP
\fB\-v\fR \fB\-\-verbose\fR
increase verbosity
.TP
\fB\-l\fR \fB\-\-loop\fR
number of loops
.TP
\fB\-t\fR \fB\-\-timewait\fR
time to wait between loops [sec]
.TP
\fB\-e\fR \fB\-\-delay\fR
delay before the scanning begins [sec]
.TP
\fB\-m\fR \fB\-\-timelimit\fR
time limit [ms] for the scanning
.TP
\fB\-a\fR \fB\-\-priority\fR
priority for the threads
.TP
\fB\-d\fR \fB\-\-database\fR
path for the database
.TP
\fB\-f\fR \fB\-\-download\fR
path for the downloader destination
.TP
\fB\-c\fR \fB\-\-commit\-int\fR
commits interval
.TP
\fB\-p\fR \fB\-\-parser\fR
number of parsers
.TP
\fB\-n\fR \fB\-\-decrap\fR
enable decrapifier (for title metadata)
.TP
\fB\-k\fR \fB\-\-keyword\fR
keyword for the decrapifier
.TP
\fB\-s\fR \fB\-\-suffix\fR
file suffix (extension)
.TP
\fB\-g\fR \fB\-\-grabber\fR
grabber to be used
.SS "Example:"
.IP
libvalhalla\-test \fB\-l\fR 2 \fB\-t\fR 5 \fB\-d\fR ./mydb.db \fB\-p\fR 1 \fB\-a\fR 15 \fB\-s\fR ogg \fB\-s\fR mp3 /home/foobar/music
.PP
Default values are:
.IP
loop=1, timewait=0, database=./valhalla.db, commit\-int=128, parser=2, priority=19,
.IP
suffix=flac,m4a,mp3,ogg, wav,wma,avi,mkv,mov,mpg,wmv, bmp,gif,jpeg,jpg,png,tga,tif,tiff
.SH AUTHOR
libvalhalla was written by Mathieu Schroeter <mathieu@schroetersa.ch>,
Benjamin Zores <ben@geexbox.org>, Fabien Brisset <fbrisset@gmail.com> and
Davide Cavalca <davide@geexbox.org>.
.PP
This manual page was written by Davide Cavalca <davide@geexbox.org>,
for the Debian project (but may be used by others).
